#  Reddit’s r/beer subreddit

### Trying to see if scraping Reddit would provide good "review" data

In [8]:
import requests
import time
import pandas as pd
import numpy as np

In [25]:
base_url = 'https://api.pushshift.io/reddit/search/comment'
#read in pushshift api to access reddit comments

In [11]:
# res = requests.get(
#     base_url,
#     params={
#         'subreddit': 'beer',
#         'size': 100
#     })

In [12]:
# res.status_code

200

In [13]:
# data = res.json()

In [14]:
# data.keys()

dict_keys(['data'])

In [26]:
def get_beer(subreddit, n_iter): #defined "get_subs" in order to pull
    df_list = []
    current_time = 1590648488  #current time from pulling first batch 
    for _ in range(n_iter): #" '_' common way to denote you're going to do something 
                            #X of times, and we don't care about the numbers before the one we name" 
        res = requests.get(
            base_url,
            params = {
                'subreddit': subreddit, #this will be able to pull from any subreddit
                'size': 300, #Max iter per pull
                'before': current_time
            }
        )
        
        df = pd.DataFrame(res.json()['data'])
        df = df.loc[:, ['created_utc', 'body', 'subreddit']] #show me everything in these columns
        df_list.append(df) 
        current_time = df.created_utc.min()
        time.sleep(3) # time delay
        
    return pd.concat(df_list, axis=0) #adds the selected columns, pulled by .loc[], together


# Tim Book code (modified)

In [27]:
df_beer = get_beer('beer', 10)
#this code iterates through data
#code won't go past 15 without hitting error

In [28]:
df_beer.shape

(3000, 3)

In [29]:
df_beer

     created_utc                                               body subreddit
0     1590641858  My bottle shop is currently doing this. I’ve t...      beer
1     1590641642  Absolutely I do understand that, better than y...      beer
2     1590641621  Hmmm does this store also happen to be a Deli?...      beer
3     1590640735  Mixed fermented beers like Lambics have probab...      beer
4     1590640695  Then as someone who manages a small business, ...      beer
..           ...                                                ...       ...
295   1589779465       You don’t need to use ice packs or anything?      beer
296   1589779038                          /r/dadjokes \n\nbless you      beer
297   1589778855                            Might be a specific hop      beer
298   1589776250                                            LIAR!!!      beer
299   1589774200                       LMK if you need help moving.      beer

[3000 rows x 3 columns]

In [31]:
#duplicate
df_beer[df_beer['body'].duplicated() == True]

     created_utc                                               body subreddit
47    1590624707                                          [deleted]      beer
58    1590618249                                          [deleted]      beer
71    1590613578                                          [deleted]      beer
212   1590539105                                          [deleted]      beer
180   1590454134                                          [deleted]      beer
190   1590451928                                               Neat      beer
195   1590450753                                          [deleted]      beer
263   1590429272                                                Yes      beer
68    1590410938  Only sell at the brewery so dont bother lookin...      beer
181   1590368541                                          [deleted]      beer
179   1590272697                                          [deleted]      beer
80    1590214494                                          [deleted]      beer
133   1590206531                                          [deleted]      beer
135   1590206412                                          [deleted]      beer
232   1590197804                                          [deleted]      beer
58    1590188411    That’s the greatest Hefeweizen IMO. Masterpiece      beer
61    1590188327  This is why I make a point to order Browns and...      beer
243   1590181844                                               Amen      beer
276   1590180799                                                  .      beer
289   1590180321                                          [deleted]      beer
269   1590126867                                          [removed]      beer
81    1590089070                                          [deleted]      beer
187   1590032156                                          [deleted]      beer
194   1590025579                                          [deleted]      beer
200   1590020769                                          [deleted]      beer
213   1590013564                                          [deleted]      beer
265   1589996782                                          [deleted]      beer
142   1589949204                                          [deleted]      beer
153   1589948192                                          [deleted]      beer
196   1589940373                                       Yes they are      beer
212   1589937384                                          [deleted]      beer
243   1589931281                                          [deleted]      beer
261   1589915574                                          [deleted]      beer
10    1589898181                                          [removed]      beer
57    1589893426  Check out these posts and comments from a whil...      beer
127   1589855987                                          [deleted]      beer
237   1589823238                                          [deleted]      beer

In [32]:
df_beer = df_beer.drop_duplicates(subset="body")

In [33]:
df_beer

     created_utc                                               body subreddit
0     1590641858  My bottle shop is currently doing this. I’ve t...      beer
1     1590641642  Absolutely I do understand that, better than y...      beer
2     1590641621  Hmmm does this store also happen to be a Deli?...      beer
3     1590640735  Mixed fermented beers like Lambics have probab...      beer
4     1590640695  Then as someone who manages a small business, ...      beer
..           ...                                                ...       ...
295   1589779465       You don’t need to use ice packs or anything?      beer
296   1589779038                          /r/dadjokes \n\nbless you      beer
297   1589778855                            Might be a specific hop      beer
298   1589776250                                            LIAR!!!      beer
299   1589774200                       LMK if you need help moving.      beer

[2963 rows x 3 columns]

In [35]:
df_beer.isnull().sum()

created_utc    0
body           0
subreddit      0
dtype: int64

In [36]:
df_beer = df_beer.drop(['created_utc'], axis=1)

In [39]:
df_beer.head(1)

                                                body subreddit
0  My bottle shop is currently doing this. I’ve t...      beer

In [ ]:
df_beer.to_csv('reddit_beer_df.csv')